ac_consultoria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls'))
]

api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('furtos/', views.furto_equipamento_list, name='furtos'),
    path('furtos/latest-period', views.fetch_latest_period, name='latest_period'),
    path('furtos/<int:pk>', views.update_furto_equipamento, name='update_furto')
]

main/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [
path('', views.index, name='index'),
    path('powerbi', views.powerbi, name='powerbi'),
    path('mapacalor', views.mapacalor, name='mapa_calor'),
    path('login', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('double-checker', views.double_checker, name='double_checker'),
    path('ocorrencias-bairros-curitiba', views.ocorrencias_bairros_curitiba, name='ocorrencias_bairros_curitiba')
]

api/models.py
from django.db import models

main/models.py
from django.db import models

class Ocorrencia(models.Model):
    ESTRUTURA_CRIMINAL_CHOICES = (
        ('OPORTUNISTA', 'Oportunista'),
        ('RECEPTACAO', 'Receptação'),
        ('QUADRILHA', 'Quadrilha')
    )

    nome = models.CharField(max_length=100)
    numero_documento =  models.CharField(max_length=100, null=True, blank=True)
    numero_bo = models.CharField(max_length=100, null=True, blank=True)
    cidade = models.CharField(max_length=100)
    placa = models.CharField(max_length=100, null=True, blank=True)
    delito = models.CharField(max_length=100)
    data = models.DateField()
    estrutura_criminal = models.CharField(max_length=11, choices=ESTRUTURA_CRIMINAL_CHOICES)

    class Meta:
        verbose_name = "Ocorrência"
        verbose_name_plural = "Ocorrências"

    def __str__(self):
        return self.nome


class FurtoEquipamento(models.Model):
    class Status(models.TextChoices):
        AGUARDANDO_GEO = 'AGUARDANDO_GEO', 'Aguardando Geocodificação'
        GEO_FALHOU = 'GEO_FALHOU', 'Falha na Geocodificação'
        AGUARDANDO_VERIFICACAO = 'AGUARDANDO_VERIFICACAO', 'Aguardando Verificação'
        VERIFICADO = 'VERIFICADO', 'Verificado'

    data_ocorrencia = models.DateField(verbose_name="Data da Ocorrência",
                                       db_index=True)

    status = models.CharField(max_length=22,
                              choices=Status.choices,
                              default=Status.AGUARDANDO_GEO,
                              db_index=True)

    logradouro = models.CharField(max_length=100)
    numero = models.CharField(max_length=30, null=True, blank=True)
    bairro = models.CharField(max_length=50, null=True, blank=True)
    cidade = models.CharField(max_length=50)
    uf = models.CharField(max_length=2, verbose_name='UF', default='PR')
    tipo_de_equipamento = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Furto de Equipamento'
        verbose_name_plural = 'Furtos de Equipamento'

    def __str__(self):
        return f"{self.tipo_de_equipamento} em {self.cidade}/{self.uf} - {self.get_status_display()}"

api/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.db.models import Max
from django.shortcuts import get_object_or_404
from rest_framework import status

from rest_framework.decorators import api_view
from rest_framework.response import Response

from main.models import FurtoEquipamento
from .serializers import FurtoEquipamentoSerializer

@login_required
@api_view(['GET'])
def furto_equipamento_list(request):
    queryset = FurtoEquipamento.objects.filter(status=FurtoEquipamento.Status.VERIFICADO)

    month = request.query_params.get('month')
    year = request.query_params.get('year')
    city = request.query_params.get('city')

    if month:
        queryset = queryset.filter(data_ocorrencia__month=month)

    if year:
        queryset = queryset.filter(data_ocorrencia__year=year)

    if city:
        queryset = queryset.filter(cidade__iexact=city)

    serializer = FurtoEquipamentoSerializer(queryset, many=True)

    return Response(serializer.data)

@login_required
@api_view(['GET'])
def fetch_latest_period(request):
    latest_date_result = FurtoEquipamento.objects.filter(
        status=FurtoEquipamento.Status.VERIFICADO
    ).aggregate(latest_date=Max('data_ocorrencia'))

    latest_date = latest_date_result.get('latest_date')
    response_data = {
        'month': latest_date.month,
        'year': latest_date.year
    }

    return Response(response_data)

@staff_member_required
@api_view(['PATCH'])
def update_furto_equipamento(request, pk):
    instance = get_object_or_404(FurtoEquipamento, pk=pk)

    serializer = FurtoEquipamentoSerializer(instance, data=request.data, partial=True)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Ocorrencia

@login_required()
def powerbi(request):
    return render(request, 'main/powerbi.html')

@login_required()
def mapacalor(request):
    return render(request, 'main/mapa_calor.html')

@login_required()
def index(request):
    return render(request, 'main/index.html')

@login_required()
def double_checker(request):
    if request.htmx.trigger_name:
        field = request.htmx.trigger_name
        search = {f'{field}__unaccent__icontains': request.GET.get(field)}
        context = {'ocorrencias': Ocorrencia.objects.filter(**search)[:6]}
        return render(request, 'main/double_checker.html#results', context)
    return render(request, 'main/double_checker.html')

@login_required()
def ocorrencias_bairros_curitiba(request):
    return render(request, 'main/ocorrencias_bairros_curitiba.html')

templates/main/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8" hx-preserve="true">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" hx-preserve="true">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/style.min.css' %}" hx-preserve="true">
    <script src="{% static 'main/js/htmx.bundle.js' %}" hx-preserve="true"></script>
    {% block head %}
    {% endblock %}
</head>
<body hx-ext="head-support">
    <div class="body-wrapper">
    <nav hx-boost="true" hx-target="#content">
        <a href="{% url 'main:powerbi' %}">Power BI</a>
        <a href="{% url 'main:mapa_calor' %}">Mapa de Calor</a>
        <a href="{% url 'main:double_checker' %}">Double Checker</a>
        <a href="{% url 'main:ocorrencias_bairros_curitiba' %}">Ocorrências por Bairro</a>
    </nav>
    <main id="content">
        {% block content %}
        {% endblock %}
    </main>
    </div>
</body>
</html>

templates/main/_partial.html
<head hx-head="merge">
    <title>{% block title %}{% endblock %}</title>
    <script>
        document.body.addEventListener('htmx:beforeSwap', () => {
            if (window.currentMap) {
                window.currentMap.off()
                window.currentMap.remove();
                const container = window.currentMap.getContainer();
                container.parentNode.removeChild(container);
                window.currentMap = null;
            }
        });
    </script>
    {% block head %}
    {% endblock %}
</head>

{% block content %}
{% endblock %}

templates/main/base.html
{% load static %}
{% load django_htmx %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/style.min.css' %}">
    {% htmx_script %}
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="body-wrapper">
    <nav>
        <a hx-get="{% url 'main:powerbi' %}"
           hx-target="#content"
           hx-push-url="true" href="#">Power BI</a>
        <a href="{% url 'main:mapa_calor' %}">Mapa de Calor</a>
        <a hx-get="{% url 'main:double_checker' %}"
           hx-target="#content"
           hx-push-url="true" href="#">Double Checker</a>
    </nav>
    <main id="content">
        {% block content %}
        {% endblock %}
    </main>
    </div>
</body>
</html>

templates/main/double_checker.html
{% extends base_template %}
{% load partials %}

{% block title %}Double Checker{% endblock %}

{% block content %}
<div class="search-page-container">
    <header class="search-header">
        <div class="search-form">
            <div class="form-group">
                <label for="name-search" class="form-label">Nome</label>
                <input type="text" id="name-search" name="nome" placeholder="Digite o nome..."
                       class="search-input" hx-get="{% url 'main:double_checker' %}" hx-target=".results-wrapper"
                       hx-trigger="keyup[key=='Enter']">
            </div>

            <div class="form-group">
                <label for="id-search" class="form-label">RG / CPF</label>
                <input type="text" id="id-search" name="numero_documento" placeholder="Digite o RG ou CPF..."
                       class="search-input" hx-get="{% url 'main:double_checker' %}" hx-target=".results-wrapper"
                       hx-trigger="keyup[key=='Enter']">
            </div>

            <div class="form-group">
                <label for="plate-search" class="form-label">Placa do Veículo</label>
                <input type="text" id="plate-search" name="placa" placeholder="Digite a placa..."
                       class="search-input" hx-get="{% url 'main:double_checker' %}" hx-target=".results-wrapper"
                       hx-trigger="keyup[key=='Enter']">
            </div>
        </div>
    </header>

    <div class="results-wrapper">
        <div class="search-feedback">
            <div class="search-feedback-icon">🔎</div>
            <h2>Digite sua pesquisa na aba ao lado</h2>
            <p>Se precisar de mais informações contate o administrador do site.</p>
        </div>
    </div>
</div>
<script>
document.body.addEventListener('htmx:beforeRequest', function(event) {
        const triggeringElement = event.detail.elt;
        if (!triggeringElement.classList.contains('search-input')) {
            return;
        }

        const allSearchInputs = document.querySelectorAll('.search-input');

        allSearchInputs.forEach(input => {
            if (input !== triggeringElement) {
                input.value = '';
            }
        });
    });
</script>
{% endblock %}

{% partialdef results %}
    {% if ocorrencias %}
        <div class="results-grid">
            {% for ocorrencia in ocorrencias %}
                <div class="card">
                    <header class="card__header">
                        <h3>{{ ocorrencia.nome|title }}</h3>
                        <span class="badge badge--{{ ocorrencia.estrutura_criminal|slugify }}">
                            {{ ocorrencia.get_estrutura_criminal_display }}</span>
                    </header>
                    <div class="card__body">
                        <p><strong>Placa:</strong> {{ ocorrencia.placa|default:"Não Informado" }}</p>
                        <p><strong>Cidade:</strong> {{ ocorrencia.cidade }}</p>
                        <p><strong>Data:</strong> {{ ocorrencia.data|date:"d/m/y" }}</p>
                        <p><strong>Nº BO:</strong> {{ ocorrencia.numero_bo|default:"Não Informado" }}</p>
                        <p><strong>RG/CPF:</strong> {{ ocorrencia.numero_documento|default:"Não Informado" }}</p>
                        <p><strong>Delito:</strong> {{ ocorrencia.delito|default:"Não Informado" }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="search-feedback">
            <div class="search-feedback-icon">📂</div>
            <h2>Nenhum resultado encontrado</h2>
            <p>Tente ajustar seus termos de pesquisa ou usar filtros diferentes.</p>
        </div>
    {% endif %}
{% endpartialdef %}

templates/main/index.html
{% load static %}
{% load django_htmx %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sobre os Dados</title>
    <link rel="stylesheet" href="{% static 'main/css/style.min.css' %}">
    {% htmx_script %}
</head>
<body>

    <div class="page-wrapper">
        <main class="landing-container">

            <h1>Sobre os Dados Apresentados</h1>

            <div class="landing-text">
                <p>
                    Todos os dados utilizados nas análises do Power BI, no mapa de calor e no Double Checker foram fornecidos por empresas e instituições públicas que participam do Grupo Integrado ao Combate de Furto de Cabos.
                </p>
                <p>
                    As informações consolidadas no Power BI e no mapa de calor do Paraná têm como base registros de furtos e danos reportados nos sistemas de gestão das empresas colaboradoras.
                </p>
                <p>
                    Este site foi criado com o objetivo de apoiar as análises e atender à demanda por uma base de dados compartilhada e segura entre todos os integrantes do GT de Furto de Cabos e os orgãos de segurança pública.
                </p>
            </div>

            <nav>
                <a href="{% url 'main:powerbi' %}">Power BI</a>
                <a href="{% url 'main:mapa_calor' %}">Mapa de Calor</a>
                <a href="{% url 'main:double_checker' %}">Double Checker</a>
                <a href="{% url 'main:ocorrencias_bairros_curitiba' %}">Ocorrências por Bairro</a>
            </nav>

        </main>
    </div>

</body>
</html>

templates/main/login.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/css/style.min.css' %}">
</head>
<body>
    <div class="page-wrapper">
        <div class="card card--login">
            <h1>Entrar na sua Conta</h1>

            <form method="post">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="errorlist">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <p class="errorlist">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn--primary">Entrar</button>
            </form>
        </div>
    </div>
</body>
</html>

templates/main/mapa_calor.html
{% extends base_template %}
{% block title %}Mapa Calor{% endblock %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/map/map-lib.css' %}" hx-preserve="true">
    <link rel="preload" href="{% static 'main/map/parana.json' %}" as="fetch" crossorigin>
    <script src="{% static 'main/map/map-lib.js' %}" hx-preserve="true"></script>
{% endblock %}

{% block content %}
    <div id="map" class="map"></div>
    <script>
        function initializeMap () {
            const {L, HeatmapOverlay, LazyLocationData} = MapLib
            const map = L.map('map', {
                zoom: 7,
                center: [-24.61, -51.32],
            });
            window.currentMap = map;

            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);

            fetch('{% static 'main/map/parana.json' %}')
                .then(response => response.json())
                .then(data => {
                    L.geoJSON(data).addTo(map);
                });

            const heatmapLayer = new HeatmapOverlay({
                radius: 15,
                blur: 0.8,
                maxOpacity: 0.6,
                scaleRadius: false,
                useLocalExtrema: false,
                latField: 'lat',
                lngField: 'lng',
                valueField: 'count',
                defaultWeight: 1,
            }).addTo(map);

            const cluster = L.markerClusterGroup().addTo(map);

            function generateMonthLabels(latestMonth) {
                let timeLabels = []
                for (let monthNumber = 0; monthNumber <= latestMonth - 1; monthNumber++) {
                    const date = new Date(2025, monthNumber, 1);
                    const monthName = new Intl.DateTimeFormat('pt-BR', {month: 'long'}).format(date);
                    const capitalizedMonthName = monthName.charAt(0).toUpperCase() + monthName.slice(1);
                    const timeLabel = '2025 - ' + capitalizedMonthName
                    timeLabels.push(timeLabel)
                }
                timeLabels.push('Total')

                return timeLabels
            }

            async function initializeTimeLabels(latestMonth = null) {
                if (latestMonth === null) {
                    const response = await fetch('api/furtos/latest-period');
                    const data = await response.json();
                    latestMonth = data.month
                }

                let timeLabels = generateMonthLabels(latestMonth)
                const times = Array.from({length: timeLabels.length}, (_, i) => i + 1)

                map.timeDimension = L.timeDimension({
                    times: times, currentTime: new Date(1)
                });

                const timeDimension = new L.Control.TimeDimensionCustom(timeLabels, {
                    autoPlay: false,
                    backwardButton: true,
                    displayDate: true,
                    forwardButton: true,
                    limitMinimumRange: 5,
                    limitSliders: true,
                    loopButton: false,
                    maxSpeed: 10,
                    minSpeed: 0.1,
                    playButton: false,
                    playReverseButton: false,
                    position: "bottomleft",
                    speedSlider: false,
                    speedStep: 0.1,
                    styleNS: "leaflet-control-timecontrol",
                    timeSlider: true,
                    timeSliderDragUpdate: false,
                    timeSteps: 1
                }).addTo(map);

                return latestMonth
            }

            async function main() {
                let currentIndex = 0

                let latestMonth;
                let markersByMonth = LazyLocationData.load();
                if (markersByMonth === null) {
                    latestMonth = await initializeTimeLabels();
                    markersByMonth = new LazyLocationData(latestMonth);
                } else {
                    latestMonth = markersByMonth.length
                    await initializeTimeLabels(latestMonth)
                }
                const totalIndex = latestMonth + 1

                map.timeDimension.on('timeload', async function (e) {
                    let newIndex = e.time;
                    if (newIndex === currentIndex) return;
                    currentIndex = newIndex
                    const dataIndex = (newIndex === totalIndex) ? 'all' : newIndex;
                    const [markers, heatmapArray] = await Promise.all([
                        markersByMonth.asMarkers(dataIndex),
                        markersByMonth.asHeatmapArray(dataIndex)
                    ]);
                    cluster.clearLayers();
                    cluster.addLayers(markers);
                    heatmapLayer.setData(heatmapArray);
                    markersByMonth.save();
                });

                map.timeDimension.fire('timeload', {time: 1});
            }

            main();
        }

        if (window.MapLib !== undefined) {
            initializeMap();
        }
        else {
            window.addEventListener('map-lib-loaded', initializeMap, {once: true});
        }
    </script>
{% endblock %}

templates/main/ocorrencias_bairros_curitiba.html
{% extends base_template %}
{% block title %}Ocorrências por Bairro{% endblock %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/map/map-lib.css' %}" hx-preserve="true">
    <link rel="preload" href="{% static 'main/map/curitiba_bairros.json' %}" as="fetch" crossorigin>
    <script src="{% static 'main/map/map-lib.js' %}" hx-preserve="true"></script>
    <style>
        .neighborhood-label-content {
            font-family: Arial, sans-serif;
            color: black;
            font-weight: bold;
            text-align: center;

            position: absolute;
            transform: translate(-50%, -50%);

            pointer-events: none;
        }
        .zoom-less-than-13 .neighborhood-name {
          display: none;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="map" class="map"></div>
    <script>
        async function initializeMap () {
            function joinFurtoCountToGeoJSON(furtoData, geojsonData) {
                const furtoCounts = {};
                for (const furto of furtoData) {
                    const neighborhoodName = furto.bairro;

                    furtoCounts[neighborhoodName] = (furtoCounts[neighborhoodName] || 0) + 1;
                }

                geojsonData.features.forEach(feature => {
                    const neighborhoodName = feature.properties.name_neighborhood;
                    feature.properties.furto_count = furtoCounts[neighborhoodName] || 0;
                });

                return geojsonData;
            }

            function style(feature) {
                const count = feature.properties.furto_count;
                const fillColor = count > 94 ? '#800026' :
                                  count > 65 ? '#BD0026' :
                                  count > 42 ? '#E31A1C' :
                                  count > 31 ? '#FC4E2A' :
                                  count > 19 ? '#FD8D3C' :
                                  count > 8  ? '#FEB24C' :
                                               '#FFEDA0';
                return {
                    fillColor: fillColor,
                    weight: 2,
                    fillOpacity: 0.7,
                    lineOpacity: 0.8,
                    lineWeight: 1.5,
                    color: '#333333'
                };
            }

            function addDivIcons(feature, layer) {
                const name = feature.properties.name_neighborhood;
                const count = feature.properties.furto_count;

                const center = layer.getBounds().getCenter();

                const html = `
                    <div class="neighborhood-label-content">
                        <span class="neighborhood-name">${name}<br></span>${count}
                    </div>
                `;

                const divIcon = L.divIcon({
                    className: 'neighborhood-label-marker',
                    html: html,
                });

                L.marker(center, {
                    icon: divIcon
                }).addTo(map);
            }

            function toggleIconClass() {
                const currentZoom = map.getZoom();

                if (currentZoom < 13) {
                    mapContainer.classList.add('zoom-less-than-13');
                } else {
                    mapContainer.classList.remove('zoom-less-than-13');
                }
            }

            const L = MapLib.L
            const map = L.map('map', {
                zoom: 11,
                center: [-25.44762, -49.28045],
                minZoom: 11
            });
            window.currentMap = map;
            const mapContainer = map.getContainer();

            L.tileLayer('https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png', {
	            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
	            maxZoom: 19
            }).addTo(map);

            [furtoData, geojsonData] = await Promise.all([
                fetch('{% url 'api:furtos'%}{% querystring city='curitiba' %}').then(response => response.json()),
                fetch('{% static 'main/map/curitiba_bairros.json' %}').then(response => response.json())
            ]);

            const neighborhoodWithFurtoCount = joinFurtoCountToGeoJSON(furtoData, geojsonData);

            L.geoJSON(
                neighborhoodWithFurtoCount, {
                    style: style,
                    onEachFeature: addDivIcons
                }
            ).addTo(map);

            map.on('zoomend', toggleIconClass);

            map.whenReady(toggleIconClass);
        }

        if (window.MapLib !== undefined) {
            initializeMap();
        }
        else {
            window.addEventListener('map-lib-loaded', initializeMap, {once: true});
        }
    </script>
{% endblock %}

templates/main/powerbi.html
{% extends base_template %}
{% load partials %}

{% block title %}Power BI{% endblock %}

{% block content %}
    {% partial content %}
{% endblock %}

{% partialdef content %}
    <iframe class="powerbi-iframe"
            sandbox="allow-same-origin allow-scripts"
            referrerpolicy="no-referrer"
            src="https://app.powerbi.com/view?r=eyJrIjoiZGNjMzRmZGUtMGZlZi00YTQyLWIxNDMtMjZhYzI3ODY0ZDI3IiwidCI6ImUzMDI1YzcyLTcwYjQtNDUzNC1iNGQwLTFkYWRlMjU2ZGQyNiJ9">
    </iframe>
{% endpartialdef content %}

{% partialdef htmx %}
    <title hx-swap-oob="true">Power BI</title>
    {% partial content %}
{% endpartialdef %}